export type Language = {
  name: string;
  nativeName: string;
  code: string;
  voice: string;
};

export const languages: Language[] = [
  {
    name: "English",
    nativeName: "English",
    code: "en",
    voice: "en-US-JennyNeural",
  },
  {
    name: "Spanish",
    nativeName: "Español",
    code: "es",
    voice: "es-ES-ElviraNeural",
  },
  {
    name: "French",
    nativeName: "Français",
    code: "fr",
    voice: "fr-FR-DeniseNeural",
  },
  {
    name: "German",
    nativeName: "Deutsch",
    code: "de",
    voice: "de-DE-KatjaNeural",
  },
  {
    name: "Portuguese",
    nativeName: "Português",
    code: "pt",
    voice: "pt-BR-FranciscaNeural",
  },
  {
    name: "Chinese",
    nativeName: "中文",
    code: "zh",
    voice: "zh-CN-XiaoxiaoNeural",
  },
  {
    name: "Japanese",
    nativeName: "日本語",
    code: "ja",
    voice: "ja-JP-NanamiNeural",
  },
  {
    name: "Korean",
    nativeName: "한국어",
    code: "ko",
    voice: "ko-KR-SunHiNeural",
  },
  {
    name: "Arabic",
    nativeName: "العربية",
    code: "ar",
    voice: "ar-SA-ZariyahNeural",
  },
  {
    name: "Hindi",
    nativeName: "हिन्दी",
    code: "hi",
    voice: "hi-IN-SwaraNeural",
  },
  {
    name: "Russian",
    nativeName: "Русский",
    code: "ru",
    voice: "ru-RU-SvetlanaNeural",
  },
  {
    name: "Italian",
    nativeName: "Italiano",
    code: "it",
    voice: "it-IT-ElsaNeural",
  },
  {
    name: "Dutch",
    nativeName: "Nederlands",
    code: "nl",
    voice: "nl-NL-ColetteNeural",
  },
  {
    name: "Turkish",
    nativeName: "Türkçe",
    code: "tr",
    voice: "tr-TR-EmelNeural",
  },
  {
    name: "Polish",
    nativeName: "Polski",
    code: "pl",
    voice: "pl-PL-ZofiaNeural",
  },
  {
    name: "Swedish",
    nativeName: "Svenska",
    code: "sv",
    voice: "sv-SE-SofieNeural",
  },
  {
    name: "Norwegian",
    nativeName: "Norsk",
    code: "nb",
    voice: "nb-NO-PernilleNeural",
  },
  {
    name: "Danish",
    nativeName: "Dansk",
    code: "da",
    voice: "da-DK-ChristelNeural",
  },
  {
    name: "Finnish",
    nativeName: "Suomi",
    code: "fi",
    voice: "fi-FI-SelmaNeural",
  },
  {
    name: "Indonesian",
    nativeName: "Indonesia",
    code: "id",
    voice: "id-ID-GadisNeural",
  },
  {
    name: "Malay",
    nativeName: "Melayu",
    code: "ms",
    voice: "ms-MY-YasminNeural",
  },
  {
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    code: "vi",
    voice: "vi-VN-HoaiMyNeural",
  },
  {
    name: "Thai",
    nativeName: "ภาษาไทย",
    code: "th",
    voice: "th-TH-PremwadeeNeural",
  },
  {
    name: "Ukrainian",
    nativeName: "Українська",
    code: "uk",
    voice: "uk-UA-PolinaNeural",
  },
  {
    name: "Czech",
    nativeName: "Čeština",
    code: "cs",
    voice: "cs-CZ-VlastaNeural",
  },
  {
    name: "Romanian",
    nativeName: "Română",
    code: "ro",
    voice: "ro-RO-AlinaNeural",
  },
  {
    name: "Hungarian",
    nativeName: "Magyar",
    code: "hu",
    voice: "hu-HU-NoemiNeural",
  },
  {
    name: "Greek",
    nativeName: "Ελληνικά",
    code: "el",
    voice: "el-GR-AthinaNeural",
  },
  {
    name: "Hebrew",
    nativeName: "עברית",
    code: "he",
    voice: "he-IL-HilaNeural",
  },
  {
    name: "Bengali",
    nativeName: "বাংলা",
    code: "bn",
    voice: "bn-IN-TanishaaNeural",
  },
  { name: "Urdu", nativeName: "اردو", code: "ur", voice: "ur-PK-UzmaNeural" },
  {
    name: "Persian",
    nativeName: "فارسی",
    code: "fa",
    voice: "fa-IR-DilaraNeural",
  },
  {
    name: "Filipino",
    nativeName: "Filipino",
    code: "fil",
    voice: "fil-PH-BlessicaNeural",
  },
  {
    name: "Tamil",
    nativeName: "தமிழ்",
    code: "ta",
    voice: "ta-IN-PallaviNeural",
  },
  {
    name: "Telugu",
    nativeName: "తెలుగు",
    code: "te",
    voice: "te-IN-ShrutiNeural",
  },
  {
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    code: "kn",
    voice: "kn-IN-SapnaNeural",
  },
  {
    name: "Malayalam",
    nativeName: "മലയാളം",
    code: "ml",
    voice: "ml-IN-SobhanaNeural",
  },
  {
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    code: "gu",
    voice: "gu-IN-DhwaniNeural",
  },
  {
    name: "Marathi",
    nativeName: "मराठी",
    code: "mr",
    voice: "mr-IN-AarohiNeural",
  },
  {
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
    code: "pa",
    voice: "pa-IN-VaaniNeural",
  },
  {
    name: "Swahili",
    nativeName: "Kiswahili",
    code: "sw",
    voice: "sw-KE-ZuriNeural",
  },
  {
    name: "Bulgarian",
    nativeName: "Български",
    code: "bg",
    voice: "bg-BG-KalinaNeural",
  },
  {
    name: "Croatian",
    nativeName: "Hrvatski",
    code: "hr",
    voice: "hr-HR-GabrijelaNeural",
  },
  {
    name: "Slovak",
    nativeName: "Slovenčina",
    code: "sk",
    voice: "sk-SK-ViktoriaNeural",
  },
  {
    name: "Lithuanian",
    nativeName: "Lietuvių",
    code: "lt",
    voice: "lt-LT-OnaNeural",
  },
  {
    name: "Latvian",
    nativeName: "Latviešu",
    code: "lv",
    voice: "lv-LV-EveritaNeural",
  },
  {
    name: "Estonian",
    nativeName: "Eesti",
    code: "et",
    voice: "et-EE-AnuNeural",
  },
  {
    name: "Catalan",
    nativeName: "Català",
    code: "ca",
    voice: "ca-ES-JoanaNeural",
  },
  {
    name: "Serbian",
    nativeName: "Српски",
    code: "sr",
    voice: "sr-RS-SophieNeural",
  },
  {
    name: "Slovenian",
    nativeName: "Slovenščina",
    code: "sl",
    voice: "sl-SI-PetraNeural",
  },
  {
    name: "Nepali",
    nativeName: "नेपाली",
    code: "ne",
    voice: "ne-NP-HemkalaNeural",
  },
  {
    name: "Amharic",
    nativeName: "አማርኛ",
    code: "am",
    voice: "am-ET-MekdesNeural",
  },
  {
    name: "Azerbaijani",
    nativeName: "Azərbaycan",
    code: "az",
    voice: "az-AZ-BanuNeural",
  },
  {
    name: "Georgian",
    nativeName: "ქართული",
    code: "ka",
    voice: "ka-GE-EkaNeural",
  },
  {
    name: "Kazakh",
    nativeName: "Қазақ",
    code: "kk",
    voice: "kk-KZ-AigulNeural",
  },
];
