import type { Metadata } from "next";
import { SiteConfig } from "@/site-config";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Read the Terms of Service for ${SiteConfig.title}. Understand your rights and obligations when using our AI-powered YouTube summary and Telegram delivery service.`,
  alternates: { canonical: `${SiteConfig.prodUrl}/terms` },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4">
      <div className="mb-12 flex flex-col gap-2">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="text-muted-foreground text-sm">
          Last updated: February 18, 2026
        </p>
      </div>

      <div className="flex flex-col gap-10">
        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            By accessing and using BriefTube (&quot;the Service&quot;), you
            accept and agree to be bound by the terms and provisions of this
            agreement. If you do not agree to these terms, please do not use the
            Service.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">2. Description of Service</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            BriefTube is a service that monitors YouTube channels, generates
            AI-powered summaries, converts them to audio, and delivers them to
            your Telegram account.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">3. User Accounts</h2>
          <ul className="text-muted-foreground flex flex-col gap-2 text-sm leading-relaxed">
            <li>You must use a valid Google account to access the Service</li>
            <li>
              You are responsible for maintaining the security of your account
            </li>
            <li>You must be at least 13 years old to use the Service</li>
            <li>
              One account per person — multiple accounts are not permitted
            </li>
          </ul>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">4. Subscription Plans</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            BriefTube offers free and paid subscription plans:
          </p>
          <ul className="text-muted-foreground flex flex-col gap-2 text-sm leading-relaxed">
            <li>
              <strong className="text-foreground">Free Plan:</strong> Limited to{" "}
              {SiteConfig.freeChannelsLimit} YouTube channels
            </li>
            <li>
              <strong className="text-foreground">Pro Plan:</strong> Unlimited
              channels and priority processing
            </li>
            <li>Subscriptions are billed monthly via Stripe</li>
            <li>You can upgrade, downgrade, or cancel at any time</li>
            <li>Refunds are handled on a case-by-case basis</li>
          </ul>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">5. Acceptable Use</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            You agree NOT to:
          </p>
          <ul className="text-muted-foreground flex flex-col gap-2 text-sm leading-relaxed">
            <li>Use the Service for any illegal purposes</li>
            <li>Attempt to circumvent usage limits or restrictions</li>
            <li>Abuse, harass, or spam the Service</li>
            <li>Reverse engineer or copy the Service</li>
            <li>Use automated tools to abuse the Service</li>
            <li>Share your account with others</li>
          </ul>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">
            6. Content and Intellectual Property
          </h2>
          <ul className="text-muted-foreground flex flex-col gap-2 text-sm leading-relaxed">
            <li>
              Generated summaries are created from publicly available YouTube
              content
            </li>
            <li>Audio summaries are for your personal use only</li>
            <li>
              Do not redistribute or resell summaries generated by the Service
            </li>
            <li>BriefTube respects copyright and DMCA</li>
          </ul>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">7. Service Availability</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            We strive to provide reliable service, but we do not guarantee 100%
            uptime. The Service may be temporarily unavailable due to
            maintenance, updates, or technical issues.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">8. Termination</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            We reserve the right to suspend or terminate your account if you
            violate these terms. You may also delete your account at any time
            from your profile settings.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">9. Disclaimer of Warranties</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            The Service is provided &quot;as is&quot; without warranties of any
            kind, either express or implied. We do not guarantee the accuracy of
            AI-generated summaries.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">10. Limitation of Liability</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            BriefTube shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages resulting from your use of the
            Service.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">11. Changes to Terms</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            We reserve the right to modify these terms at any time. We will
            notify users of significant changes via email or through the
            Service.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-xl font-semibold">12. Contact</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            For questions about these Terms of Service:
          </p>
          <a
            href="mailto:contact@brief-tube.com"
            className="text-sm text-red-400 underline hover:text-red-300"
          >
            contact@brief-tube.com
          </a>
        </section>
      </div>
    </div>
  );
}
