-- Anonymous usage tracking for Chrome extension
-- device_id = UUID generated by extension, stored in chrome.storage.local
CREATE TABLE IF NOT EXISTS extension_anon_usage (
  device_id text NOT NULL,
  usage_date date NOT NULL DEFAULT CURRENT_DATE,
  summaries_count integer NOT NULL DEFAULT 0,
  last_video_id text,
  last_user_agent text,
  last_ip text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (device_id, usage_date)
);

CREATE INDEX IF NOT EXISTS idx_extension_anon_usage_date
  ON extension_anon_usage(usage_date);

-- Authenticated free-tier usage tracking
CREATE TABLE IF NOT EXISTS extension_user_usage (
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  usage_date date NOT NULL DEFAULT CURRENT_DATE,
  summaries_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, usage_date)
);

CREATE INDEX IF NOT EXISTS idx_extension_user_usage_date
  ON extension_user_usage(usage_date);

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS extension_installed_at timestamptz;

ALTER TABLE extension_anon_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE extension_user_usage ENABLE ROW LEVEL SECURITY;

CREATE POLICY "extension_user_usage_self_read" ON extension_user_usage
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION increment_extension_anon_usage(
  p_device_id text,
  p_video_id text,
  p_user_agent text,
  p_ip text
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_count integer;
BEGIN
  INSERT INTO extension_anon_usage (device_id, usage_date, summaries_count, last_video_id, last_user_agent, last_ip)
  VALUES (p_device_id, CURRENT_DATE, 1, p_video_id, p_user_agent, p_ip)
  ON CONFLICT (device_id, usage_date) DO UPDATE SET
    summaries_count = extension_anon_usage.summaries_count + 1,
    last_video_id = EXCLUDED.last_video_id,
    last_user_agent = EXCLUDED.last_user_agent,
    last_ip = EXCLUDED.last_ip,
    updated_at = now()
  RETURNING summaries_count INTO new_count;
  RETURN new_count;
END;
$$;

CREATE OR REPLACE FUNCTION increment_extension_user_usage(
  p_user_id uuid
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_count integer;
BEGIN
  INSERT INTO extension_user_usage (user_id, usage_date, summaries_count)
  VALUES (p_user_id, CURRENT_DATE, 1)
  ON CONFLICT (user_id, usage_date) DO UPDATE SET
    summaries_count = extension_user_usage.summaries_count + 1,
    updated_at = now()
  RETURNING summaries_count INTO new_count;
  RETURN new_count;
END;
$$;

COMMENT ON TABLE extension_anon_usage IS 'Daily summary count per device (no account). Used by Chrome extension free tier.';
COMMENT ON TABLE extension_user_usage IS 'Daily summary count per user for free-tier quota enforcement in Chrome extension.';
