import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { createClient, createAdminClient } from "@/lib/supabase/server";
import { env } from "@/lib/env";
import { Button } from "@/components/ui/button";
import { LettersList } from "./_components/letters-list";

export default async function AdminLettersPage() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!env.ADMIN_USER_ID || user?.id !== env.ADMIN_USER_ID) {
    redirect("/dashboard");
  }

  const admin = createAdminClient();
  const { data: letters } = await admin
    .from("weekly_letters")
    .select(
      "id, episode_number, week_start, week_end, status, title, subject, scheduled_at, sent_at, recipient_count, created_at, updated_at",
    )
    .order("episode_number", { ascending: false });

  return (
    <div className="flex flex-col gap-6">
      <Button asChild variant="ghost" size="sm" className="-ml-2 w-fit">
        <Link href="/dashboard/admin">
          <ArrowLeft className="size-4" />
          Back to admin
        </Link>
      </Button>
      <div className="flex flex-col gap-1">
        <h1 className="text-base font-semibold">Weekly letters</h1>
        <p className="text-muted-foreground text-xs">
          Narrative serial letters sent to the community. Each letter is one
          episode in an ongoing arc. Generated by Léa from the week&apos;s
          shipped features and changelog.
        </p>
      </div>
      <LettersList
        initialLetters={
          (letters ?? []) as unknown as Parameters<
            typeof LettersList
          >[0]["initialLetters"]
        }
      />
    </div>
  );
}
